version: 2
updates:
  - package-ecosystem: npm
    directory: /Editor
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      tiptap:
        patterns:
          - "@tiptap/*"

  - package-ecosystem: npm
    directory: /Website
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
